(function(g){var window=this;var tHa=function(a,b){return g.Qb(a,b)},Z5=function(a,b,c){a.C.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Qm(a.C,b,c)},uHa=function(a,b){var c=[];
g.aj(b,function(d){try{var e=g.En.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Dn(e)&&c.push(d)},a);
return c},vHa=function(a,b){var c=uHa(a,b);
g.Db(c,function(d){g.En.prototype.remove.call(this,d)},a)},wHa=function(a){if(a.ke){if(a.ke.locationOverrideToken)return{locationOverrideToken:a.ke.locationOverrideToken};
if(null!=a.ke.latitudeE7&&null!=a.ke.longitudeE7)return{latitudeE7:a.ke.latitudeE7,longitudeE7:a.ke.longitudeE7}}return null},xHa=function(a,b){g.kb(a,b)||a.push(b)},b6=function(a){var b=0,c;
for(c in a)b++;return b},yHa=function(a,b){var c=b instanceof g.Cc?b:g.Ic(b,/^data:image\//i.test(b));
a.src=g.Dc(c)},c6=function(){},zHa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},AHa=function(a){if(a.Af&&"function"==typeof a.Af)return a.Af();
if("string"===typeof a)return a.split("");if(g.Oa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Mb(a)},BHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Oa(a)||"string"===typeof a)g.Db(a,b,void 0);else{if(a.Ig&&"function"==typeof a.Ig)var c=a.Ig();else if(a.Af&&"function"==typeof a.Af)c=void 0;else if(g.Oa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Nb(a);d=AHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},CHa=function(a,b,c,d){var e=new g.Em(null,void 0);
a&&g.Fm(e,a);b&&g.Gm(e,b);c&&g.Hm(e,c);d&&(e.B=d);return e},d6=function(a,b){g.qo[a]=!0;
var c=g.oo();c&&c.publish.apply(c,arguments);g.qo[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Bm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",DHa(this,a.capabilities||""),EHa(this,a.experiments||""))},DHa=function(a,b){a.capabilities.clear();
g.Ge(b.split(","),g.Sa(tHa,FHa)).forEach(function(c){a.capabilities.add(c)})},EHa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},GHa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},HHa=function(a){return new f6(a)},IHa=function(a){return Array.isArray(a)?g.Mc(a,HHa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return Array.isArray(a)?"["+g.Mc(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},JHa=function(a){return g.Mc(a,function(b){return{key:b.id,
name:b.name}})},k6=function(a,b){return g.gb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},l6=function(a,b){return g.gb(a,function(c){return g6(c,b)})},KHa=function(){var a=(0,g.pt)();
a&&vHa(a,a.u.cj(!0))},m6=function(){var a=g.tt("yt-remote-connected-devices")||[];
g.Ab(a);return a},LHa=function(a){if(g.lb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Mc(a,function(d,e){return 0==e?d:d.substring(c.length)})},MHa=function(a){g.rt("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.tt("yt-remote-device-id");a||(a=j6(),g.rt("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.kb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.kb(a,b);g.vt()&&g.Cb(a,b);a=LHa(a);if(g.lb(a))try{g.cq("remote_sid")}catch(c){}else try{g.aq("remote_sid",a.join(","),-1)}catch(c){}},NHa=function(){return g.tt("yt-remote-session-browser-channel")},OHa=function(){return g.tt("yt-remote-local-screens")||[]},PHa=function(){g.rt("yt-remote-lounge-token-expiration",!0,86400)},QHa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Mc(OHa(),function(d){return d.loungeToken}),c=g.Mc(a,function(d){return d.loungeToken});
g.hh(c,function(d){return!g.kb(b,d)})&&PHa();
g.rt("yt-remote-local-screens",a,31536E3)},RHa=function(a,b){g.rt("yt-remote-session-browser-channel",a);
g.rt("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.kb(c,d)||c.push(d);MHa(c);p6()},q6=function(a){a||(g.ut("yt-remote-session-screen-id"),g.ut("yt-remote-session-video-id"));
p6();a=m6();g.pb(a,o6());MHa(a)},SHa=function(){if(!r6){var a=g.On();
a&&(r6=new g.yn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},THa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},UHa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?VHa(a.shift(),function(){s6(a)}):t6()},WHa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},VHa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.gd(d,g.kg(a));(document.head||document.documentElement).appendChild(d)},t6=function(){var a=UHa();
a&&a(!1,"No cast extension found")},YHa=function(){if(XHa){var a=2,b=UHa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;VHa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},ZHa=function(){YHa();
var a=(a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/))?parseInt(a[1],10):0;var b=[];if(0!=a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}b.push("//www.gstatic.com/eureka/clank/cast_sender.js");s6(b)},u6=function(a,b,c){g.B.call(this);
this.I=null!=c?(0,g.z)(a,c):a;this.qf=b;this.F=(0,g.z)(this.KI,this);this.u=!1;this.B=0;this.C=this.Xa=null;this.D=[]},v6=function(a,b,c){g.B.call(this);
this.D=null!=c?a.bind(c):a;this.qf=b;this.C=null;this.u=!1;this.B=0;this.Xa=null},w6=function(a){a.Xa=g.zm(function(){a.Xa=null;
a.u&&!a.B&&(a.u=!1,w6(a))},a.qf);
var b=a.C;a.C=null;a.D.apply(null,b)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return zHa(a)},y6=function(){},z6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},B6=function(a){A6.dispatchEvent(new $Ha(A6,a))},$Ha=function(a){g.rl.call(this,"statevent",a)},C6=function(){},aIa=function(){},cIa=function(a){return(a=bIa(a))?new ActiveXObject(a):new XMLHttpRequest},bIa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},D6=function(a,b,c,d){this.u=a;
this.B=b;this.N=c;this.K=d||1;this.F=45E3;this.D=new g.g1(this);this.C=new g.ym;this.C.setInterval(250)},eIa=function(a,b,c){a.co=1;
a.bk=$5(b.clone());a.mm=c;a.I=!0;dIa(a,null)},E6=function(a,b,c,d,e){a.co=1;
a.bk=$5(b.clone());a.mm=null;a.I=c;e&&(a.FF=!1);dIa(a,d)},dIa=function(a,b){a.Un=g.A();
F6(a);a.Uk=a.bk.clone();a6(a.Uk,"t",a.K);a.Oq=0;a.le=a.u.Ov(a.u.xq()?b:null);0<a.Ew&&(a.iu=new v6((0,g.z)(a.HG,a,a.le),a.Ew));a.D.xa(a.le,"readystatechange",a.RP);var c=a.Nl?g.Wb(a.Nl):{};a.mm?(a.Mu="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.le.send(a.Uk,a.Mu,a.mm,c)):(a.Mu="GET",a.FF&&!g.we&&(c.Connection="close"),a.le.send(a.Uk,a.Mu,null,c));a.u.Gh(1)},hIa=function(a,b,c){for(var d=!0;!a.vl&&a.Oq<c.length;){var e=fIa(a,c);
if(e==G6){4==b&&(a.vk=4,B6(15),d=!1);break}else if(e==gIa){a.vk=4;B6(16);d=!1;break}else H6(a,e)}4==b&&0==c.length&&(a.vk=1,B6(17),d=!1);a.Ph=a.Ph&&d;d||(I6(a),J6(a))},fIa=function(a,b){var c=a.Oq,d=b.indexOf("\n",c);
if(-1==d)return G6;c=Number(b.substring(c,d));if(isNaN(c))return gIa;d+=1;if(d+c>b.length)return G6;var e=b.substr(d,c);a.Oq=d+c;return e},jIa=function(a,b){a.Un=g.A();
F6(a);var c=b?window.location.hostname:"";a.Uk=a.bk.clone();Z5(a.Uk,"DOMAIN",c);Z5(a.Uk,"t",a.K);try{a.Uh=new ActiveXObject("htmlfile")}catch(n){I6(a);a.vk=7;B6(22);J6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in K6)h=K6[h];else if(h in iIa)h=K6[h]=iIa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
K6[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.dd(g.gc("b/12014412"),d+"</body></html>");a.Uh.open();a.Uh.write(g.$c(c));a.Uh.close();a.Uh.parentWindow.m=(0,g.z)(a.jP,a);a.Uh.parentWindow.d=(0,g.z)(a.FE,a,!0);a.Uh.parentWindow.rpcClose=(0,g.z)(a.FE,a,!1);c=a.Uh.createElement("DIV");a.Uh.parentWindow.document.body.appendChild(c);d=g.Hc(a.Uk.toString());d=g.kd(g.Dc(d));d=g.dd(g.gc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ed(c,d);a.u.Gh(1)},F6=function(a){a.oz=g.A()+a.F;
kIa(a,a.F)},kIa=function(a,b){if(null!=a.mo)throw Error("WatchDog timer not null");
a.mo=z6((0,g.z)(a.sP,a),b)},L6=function(a){a.mo&&(g.v.clearTimeout(a.mo),a.mo=null)},J6=function(a){a.u.GB()||a.vl||a.u.us(a)},I6=function(a){L6(a);
g.Yf(a.iu);a.iu=null;a.C.stop();g.KBa(a.D);if(a.le){var b=a.le;a.le=null;b.abort();b.dispose()}a.Uh&&(a.Uh=null)},H6=function(a,b){try{a.u.xE(a,b),a.u.Gh(4)}catch(c){}},mIa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;lIa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){mIa(a,b,c,d,f)},f)})}},lIa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
yHa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},N6=function(a){g.Ol.call(this);
this.headers=new g.Bm;this.ca=a||null;this.C=!1;this.Y=this.u=null;this.va=this.P="";this.I=0;this.D="";this.F=this.ka=this.N=this.fa=!1;this.K=0;this.W=null;this.Ca="";this.X=this.ea=!1},nIa=function(a){return g.se&&g.Vd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},oIa=function(a){return"content-type"==a.toLowerCase()},qIa=function(a,b){a.C=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.D=b;a.I=5;pIa(a);O6(a)},pIa=function(a){a.fa||(a.fa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},sIa=function(a){if(a.C&&"undefined"!=typeof g.l1)if(a.Y[1]&&4==P6(a)&&2==a.getStatus())Q6(a,"Local request error detected and ignored");
else if(a.N&&4==P6(a))g.zm(a.uE,0,a);else if(a.dispatchEvent("readystatechange"),4==P6(a)){Q6(a,"Request complete");a.C=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.td(1,String(a.P));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!rIa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<P6(a)?a.u.statusText:""}catch(m){l=""}a.D=l+" ["+a.getStatus()+"]";pIa(a)}}finally{O6(a)}}},O6=function(a,b){if(a.u){tIa(a);
var c=a.u,d=a.Y[0]?g.La:null;a.u=null;a.Y=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},tIa=function(a){a.u&&a.X&&(a.u.ontimeout=null);
a.W&&(g.v.clearTimeout(a.W),a.W=null)},P6=function(a){return a.u?a.u.readyState:0},R6=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},Q6=function(a,b){return b+" ["+a.va+" "+a.P+" "+a.getStatus()+"]"},uIa=function(a){this.u=a;
this.B=new y6},vIa=function(a){var b=S6(a.u,a.Eo,"/mail/images/cleardot.gif");
$5(b);mIa(b.toString(),5E3,(0,g.z)(a.JH,a),3,2E3);a.Gh(1)},U6=function(a){var b=a.u.N;
if(null!=b)B6(5),b?(B6(11),T6(a.u,a,!1)):(B6(12),T6(a.u,a,!0));else if(a.Xf=new D6(a,void 0,void 0,void 0),a.Xf.Nl=a.Cw,b=a.u,b=S6(b,b.xq()?a.kp:null,a.Dw),B6(5),!g.se||g.Wd(10))a6(b,"TYPE","xmlhttp"),E6(a.Xf,b,!1,a.kp,!1);else{a6(b,"TYPE","html");var c=a.Xf;a=!!a.kp;c.co=3;c.bk=$5(b.clone());jIa(c,a)}},V6=function(a,b,c){this.Ia=1;
this.u=[];this.C=[];this.D=new y6;this.K=a||null;this.N=null!=b?b:null;this.F=c||!1},wIa=function(a,b){this.u=a;
this.map=b;this.context=null},xIa=function(a,b,c,d){g.rl.call(this,"timingevent",a);
this.size=b;this.lq=d},yIa=function(a){g.rl.call(this,"serverreachability",a)},CIa=function(a){AIa(a);
if(3==a.Ia){var b=a.Rp++,c=a.Or.clone();Z5(c,"SID",a.B);Z5(c,"RID",b);Z5(c,"TYPE","terminate");W6(a,c);b=new D6(a,a.B,b,void 0);b.co=2;b.bk=$5(c.clone());yHa(new Image,b.bk.toString());b.Un=g.A();F6(b)}BIa(a)},DIa=function(a){a.iI(1,0);
a.Or=S6(a,null,a.Bw);X6(a)},AIa=function(a){a.gk&&(a.gk.abort(),a.gk=null);
a.Id&&(a.Id.cancel(),a.Id=null);a.ej&&(g.v.clearTimeout(a.ej),a.ej=null);Y6(a);a.Pf&&(a.Pf.cancel(),a.Pf=null);a.kk&&(g.v.clearTimeout(a.kk),a.kk=null)},EIa=function(a,b){if(0==a.Ia)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new wIa(a.bM++,b));2!=a.Ia&&3!=a.Ia||X6(a)},FIa=function(a){var b=0;
a.Id&&b++;a.Pf&&b++;return b},X6=function(a){a.Pf||a.kk||(a.kk=z6((0,g.z)(a.EE,a),0),a.Zm=0)},HIa=function(a,b){if(1==a.Ia){if(!b){a.Rp=Math.floor(1E5*Math.random());
var c=a.Rp++,d=new D6(a,"",c,void 0);d.Nl=a.uk;var e=Z6(a),f=a.Or.clone();Z5(f,"RID",c);Z5(f,"CVER","1");W6(a,f);eIa(d,f,e);a.Pf=d;a.Ia=2}}else 3==a.Ia&&(b?GIa(a,b):0==a.u.length||a.Pf||GIa(a))},GIa=function(a,b){if(b)if(6<a.wl){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Rp-1;var d=Z6(a)}else c=b.N,d=b.mm;else c=a.Rp++,d=Z6(a);var e=a.Or.clone();Z5(e,"SID",a.B);Z5(e,"RID",c);Z5(e,"AID",a.nn);W6(a,e);c=new D6(a,a.B,c,a.Zm+1);c.Nl=a.uk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Pf=c;eIa(c,e,d)},W6=function(a,b){if(a.lf){var c=a.lf.jB();
c&&g.Fb(c,function(d,e){Z5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.wl&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Dm:e.Dm},f++){e.Dm=a.u[f].u;var h=a.u[f].map;e.Dm=6>=a.wl?f:e.Dm-d;try{g.Fb(h,function(l){return function(m,n){c.push("req"+l.Dm+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Dm+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},IIa=function(a){a.Id||a.ej||(a.I=1,a.ej=z6((0,g.z)(a.DE,a),0),a.Lm=0)},$6=function(a){if(a.Id||a.ej||3<=a.Lm)return!1;
a.I++;a.ej=z6((0,g.z)(a.DE,a),JIa(a,a.Lm));a.Lm++;return!0},T6=function(a,b,c){a.Ju=c;
a.ni=b.qj;a.F||DIa(a)},Y6=function(a){null!=a.Bl&&(g.v.clearTimeout(a.Bl),a.Bl=null)},JIa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.lf&&(c=null);var d=(0,g.z)(a.BQ,a);c||(c=new g.Em("//www.google.com/images/cleardot.gif"),$5(c));lIa(c.toString(),1E4,d)}else B6(2);KIa(a,b)},KIa=function(a,b){a.Ia=0;
a.lf&&a.lf.wA(b);BIa(a);AIa(a)},BIa=function(a){a.Ia=0;
a.ni=-1;if(a.lf)if(0==a.C.length&&0==a.u.length)a.lf.Ev();else{g.sb(a.C);var b=g.sb(a.u);a.C.length=0;a.u.length=0;a.lf.Ev(b)}},S6=function(a,b,c){var d=g.Mm(c);
if(""!=d.u)b&&g.Gm(d,b+"."+d.u),g.Hm(d,d.D);else{var e=window.location;d=CHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Uo&&g.Fb(a.Uo,function(f,h){Z5(d,h,f)});
Z5(d,"VER",a.wl);W6(a,d);return d},LIa=function(){},MIa=function(){this.u=[];
this.B=[]},NIa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.B.call(this);
this.u=new g.F(this.cP,0,this);g.C(this,this.u);this.qf=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},c7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.Y=a;this.I=b;this.C=new g.xn;this.B=new b7(this.dQ,this);this.u=null;this.W=!1;this.F=null;this.P="";this.N=this.D=0;this.K=[];this.ca=c;this.X=d},OIa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.Ju,sessionId:a.u.B,arrayId:a.u.nn}},PIa=function(a,b){a.N=b||0;
a.B.stop();d7(a);a.u&&(3==a.u.getState()&&HIa(a.u),CIa(a.u));a.N=0},e7=function(a){return!!a.u&&3==a.u.getState()},d7=function(a){if(a.u){var b=a.X(),c=a.u.uk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.uk=c}},QIa=function(a,b){(a.I.loungeIdToken=b)||a.B.stop()},f7=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.td(4,a))||"";b&&(this.port=":"+b);this.domain=g.ud(a)||"";a=g.Sc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ac(a,"10.0")&&(this.B=!1))},g7=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Fd(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.D,d,!0),onError:g.Sa(a.C,e),vg:g.Sa(a.F,e)};c&&(a.jc=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Vp(b,a)},UIa=function(){var a=RIa;
SIa();i7.push(a);TIa(i7)},j7=function(a,b){SIa();
var c=i7,d=VIa(a,String(b));g.lb(c)?WIa(d):(TIa(c),g.Db(c,function(e){e(d)}))},SIa=function(){i7||(i7=g.Ka("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",i7,void 0))},WIa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},TIa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];g.Db(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},VIa=function(a,b){var c=(g.A()-XIa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.O.call(this);
this.I=a;this.screens=[]},YIa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},ZIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ge(a.screens,function(f){return!!k6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=YIa(a,b[d])||c;return c},$Ia=function(a,b){var c=a.screens.length;
a.screens=g.Ge(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.O.call(this);
this.I=a;this.F=b;this.C=c;this.D=d;this.B=0;this.u=null;this.Xa=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.u=NaN;p7(this);this.info("Initializing with "+i6(this.screens))},aJa=function(a){if(a.screens.length){var b=g.Mc(a.screens,function(d){return d.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.z)(a.SI,a),(0,g.z)(a.RI,a))}},p7=function(a){if(g.$n("deprecate_pair_servlet_enabled"))return ZIa(a,[]);
var b=IHa(OHa());b=g.Ge(b,function(c){return!c.uuid});
return ZIa(a,b)},r7=function(a,b){QHa(g.Mc(a.screens,GHa));
b&&PHa()},t7=function(a,b){g.O.call(this);
this.I=b;var c=g.tt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.kb(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;s7("Initialized with "+g.Dj(this.u))},bJa=function(a,b,c){var d=g7(a.F,"/pairing/get_screen_availability");
h7(a.F,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},u7=function(a,b){a:if(b6(b)!=b6(a.u))var c=!1;
else{c=g.Nb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Dj(a.u)),a.u=b,a.V("screenChange"));cJa(a)},v7=function(a){isNaN(a.C)||g.no(a.C);
a.C=g.lo((0,g.z)(a.sy,a),0<a.D&&a.D<g.A()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},dJa=function(a){var b={};
g.Db(a.I(),function(c){c.token?b[c.token]=c.id:this.od("Requesting availability of screen w/o lounge token.")});
return b},cJa=function(a){a=g.Nb(g.Gb(a.u,function(b){return b}));
g.Ab(a);a.length?g.rt("yt-remote-online-screen-ids",a.join(","),60):g.ut("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.u=this.B=null;this.C=[];this.D={};eJa(this)},gJa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.lg();if(h=(c?l6(h,c):null)||l6(h,b)){h.uuid=b;var l=x7(a,h);bJa(a.u,l,function(m){e(m?l:null)})}else c?fJa(a,c,(0,g.z)(function(m){var n=x7(this,new f6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));bJa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},hJa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},fJa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={jc:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Vp(g7(a.F,"/pairing/get_lounge_token_batch"),e)},iJa=function(a){a.screens=a.B.lg();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.screens))},eJa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.z)(a.YI,a));iJa(a);a.C=IHa(g.tt("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+i6(a.C));a.u=new t7(a.F,(0,g.z)(a.lg,a,!0));a.u.subscribe("screenChange",(0,g.z)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.rt("yt-remote-automatic-screen-cache",g.Mc(a.C,GHa)));y7(a);a.D[b.uuid]=b.id;g.rt("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.tt("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.O.call(this);
this.Y=c;this.N=a;this.u=b;this.K=null},A7=function(a,b){j7(a.Y,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.B=null;this.C=0;this.F=(0,g.z)(this.eR,this);this.D=(0,g.z)(this.zP,this);this.C=g.lo((0,g.z)(function(){jJa(this,null)},this),12E4)},kJa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Dj(void 0));
var b={type:"getMdxSessionStatus"};a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.La,(0,g.z)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Dj(b))},jJa=function(a,b){g.no(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.z)(a.Vt,a),d=(0,g.z)(a.tg,a);a.zB(b,c,d,5)}}else a.tg(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.I=null;this.P="";this.ca=c;this.W=null;this.F=g.La;this.D=NaN;this.X=(0,g.z)(this.hR,this);this.B=g.La},lJa=function(a){a.B=a.N.OG(a.P,a.u.label,a.u.friendlyName,(0,g.z)(function(b){this.B=g.La;
this.Vt(b)},a),(0,g.z)(function(b){this.B=g.La;
this.tg(b)},a))},mJa=function(a){var b={};
b.pairingCode=a.P;b.theme=a.ca;SHa()&&(b.env_useStageMdx=1);return g.Dd(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.B=g.lo((0,g.z)(this.on,this,null),150)},E7=function(a,b,c,d){g.O.call(this);
this.B=a;this.K=b||"233637DE";this.I=c||"cl";this.N=d||!1;this.u=null;this.F=!1;this.C=[];this.D=(0,g.z)(this.uO,this)},nJa=function(a,b){return b?g.gb(a.C,function(c){return g6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},RIa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.F||!!a.C.length||!!a.u},H7=function(a,b,c){b!=a.u&&(g.Yf(a.u),(a.u=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.u):a.V("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.z)(a.BE,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.on(null)):a.V("yt-remote-cast2-session-change",null))},oJa=function(a){var b=a.B.NG(),c=a.u&&a.u.u;
a=g.Mc(b,function(d){c&&g6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=nJa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},uJa=function(a,b,c,d,e,f,h,l){l?I7("Cannot initialize because disabled by Mdx config."):pJa()?qJa(b,e,f,h)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?rJa(a,c):(window.__onGCastApiAvailable=function(m,n){m?rJa(a,c):(K7("Failed to load cast API: "+n),L7(!1),J7(!1),g.ut("yt-remote-cast-available"),g.ut("yt-remote-cast-receiver"),
sJa(),c(!1))},d?g.xo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?ZHa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(YHa(),s6(tJa.map(WHa))))):I7("Cannot initialize because not running Chrome")},sJa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);vJa(!1);g.to(N7);N7.length=0},O7=function(){return!!g.tt("yt-remote-cast-installed")},wJa=function(){var a=g.tt("yt-remote-cast-receiver");
return a?a.friendlyName:null},xJa=function(){I7("clearCurrentReceiver");
g.ut("yt-remote-cast-receiver")},yJa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.so("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},pJa=function(){var a=0<=g.Sc.search(/ (CrMo|Chrome|CriOS)\//);
return g.bA||a},zJa=function(a,b){M7().init(a,b)},qJa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.rt("yt-remote-cast-available",f);d6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){I7("onReceiverSelected: "+f.friendlyName);
g.rt("yt-remote-cast-receiver",f);d6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){I7("onReceiverResumed: "+f.friendlyName);
g.rt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){I7("onSessionChange: "+h6(f));
f||g.ut("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.Ka("yt.mdx.remote.cloudview.instance_")},rJa=function(a,b){L7(!0);
J7(!1);zJa(a,function(c){c?(vJa(!0),g.uo("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.ut("yt-remote-cast-available"),g.ut("yt-remote-cast-receiver"),sJa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.rt("yt-remote-cast-installed",a)},P7=function(){return!!g.Ka("yt.mdx.remote.cloudview.apiReady_")},vJa=function(a){I7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.K=this.N=0;this.u=null;this.hasNext=this.ri=!1;this.P=this.I=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.ri=!1;a.hasNext=!1;a.N=0;a.K=g.A();a.F=0;a.B=0;a.I=0;a.P=0;a.D=NaN;a.C=!1},U7=function(a){return a.Ib()?(g.A()-a.K)/1E3:0},V7=function(a,b){a.N=b;
a.K=g.A()},W7=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.K)/1E3+a.N;
case -1E3:return 0}return a.N},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Xb(a.u);b.hasPrevious=a.ri;b.hasNext=a.hasNext;b.playerTime=a.N;b.playerTimeAt=a.K;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.I;b.loadedTime=a.P;b.liveIngestionTime=a.D;return b},$7=function(a,b){g.O.call(this);
this.Ia=0;this.C=a;this.F=[];this.D=new MIa;this.B=this.u=null;this.N=(0,g.z)(this.QM,this);this.I=(0,g.z)(this.Sp,this);this.K=(0,g.z)(this.PM,this);this.P=(0,g.z)(this.XM,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Gy,this),AJa(this))):c=3;0!=c&&(b?this.Gy(c):g.lo((0,g.z)(function(){this.Gy(c)},this),0));
var d=yJa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.P)},a8=function(a){return new S7(a.C.getPlayerContextData())},AJa=function(a){g.Db("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Sa(this.qO,b),this))},a)},BJa=function(a){g.Db(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a){return 1==a.getState()},c8=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},e8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.C.sendMessage(b,c)},d8=function(a,b){BJa(a);
a.C.setPlayerContextData(Y7(b));AJa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.N),a.B.removeMediaListener(a.I),a.Sp(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.N),a.B.addMediaListener(a.I),a.B.media.length&&a.Sp(a.B.media[0]))},CJa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());d8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.z)(function(d){this.od("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.od("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.O.call(this);
this.F=NaN;this.X=!1;this.N=this.K=this.P=this.W=NaN;this.Y=[];this.D=this.I=this.C=this.Gb=this.u=null;this.fa=a;this.Y.push(g.Io(window,"beforeunload",(0,g.z)(this.LI,this)));this.B=[];this.Gb=new S7;this.ca=b.id;this.u=DJa(this,c);this.u.subscribe("handlerOpened",this.UM,this);this.u.subscribe("handlerClosed",this.RM,this);this.u.subscribe("handlerError",this.SM,this);this.u.subscribe("handlerMessage",this.TM,this);QIa(this.u,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Gb.videoId;
g.vt()&&g.rt("yt-remote-session-video-id",d)},this)},i8=function(a){j7("conn",a)},DJa=function(a,b){return new c7(g7(a.fa,"/bc"),b,!1,function(){return a.KG()})},j8=function(a,b){a.V("proxyStateChange",b)},EJa=function(a){a.F=g.lo((0,g.z)(function(){i8("Connecting timeout");
this.Um(1)},a),2E4)},k8=function(a){g.no(a.F);
a.F=NaN},l8=function(a){g.no(a.W);
a.W=NaN},FJa=function(a){m8(a);
a.P=g.lo((0,g.z)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.no(a.P);
a.P=NaN},HJa=function(a,b){b&&(k8(a),l8(a));
var c=e7(a.u)&&isNaN(a.F);b==c?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.yB()&&a.Gb.reset(),j8(a,1),n8(a,"getNowPlaying"),GJa(a)):a.Um(1)},IJa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Gb.videoId&&(g.Tb(b.params)?a.Gb.u=null:a.Gb.u=b.params,a.V("remotePlayerChange"))},JJa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Gb.listId=b.params.listId||a.Gb.listId;X7(a.Gb,c,d);a.V("remoteQueueChange")},LJa=function(a,b){b.params=b.params||{};
JJa(a,b);KJa(a,b);a.V("autoplayDismissed")},KJa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.Gb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Gb.playerState&&(c=-1E3);a.Gb.playerState=c;c=Number(b.params.loadedTime);a.Gb.P=isNaN(c)?0:c;c=Number(b.params.duration);a.Gb.I=isNaN(c)?0:c;c=a.Gb;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.Gb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.Gb.playerState?FJa(a):m8(a);a.V("remotePlayerChange")},MJa=function(a,b){if(-1E3!=
a.Gb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Gb.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.Gb,isNaN(c)?0:c);a.V("remotePlayerChange")}},NJa=function(a,b){var c="true"==b.params.muted;
a.Gb.volume=parseInt(b.params.volume,10);a.Gb.muted=c;a.V("remotePlayerChange")},OJa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},PJa=function(a,b){var c="true"==b.params.hasNext;
a.Gb.ri="true"==b.params.hasPrevious;a.Gb.hasNext=c;a.V("previousNextChange")},GJa=function(a){g.no(a.N);
a.N=g.lo((0,g.z)(a.Um,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Dj(c)):i8("Sending: action="+b);
a.u.sendMessage(b,c)},o8=function(a){n7.call(this,"ScreenServiceProxy");
this.nf=a;this.u=[];this.u.push(this.nf.$_s("screenChange",(0,g.z)(this.IJ,this)));this.u.push(this.nf.$_s("onlineScreenChange",(0,g.z)(this.XN,this)))},UJa=function(a,b){b=g.L("MDX_CONFIG")||b;
KHa();p6();p8||(p8=new f7(b?b.loungeApiHost:void 0),SHa()&&(p8.u="/api/loungedev"));q8||(q8=g.Ka("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",q8,void 0));QJa();var c=r8();if(!c){var d=new w7(p8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1,m=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial,m=!!b.disableCastApi);uJa(a,d,function(n){n?s8()&&R7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){d6("yt-remote-receiver-availability-change")})},
e,f,h,l,m)}b&&!g.Ka("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Dj(b)),u8.push(g.so("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")})),u8.push(g.so("yt-remote-cast2-receiver-selected",function(){v8(null);
d6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.so("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.so("yt-remote-cast2-session-change",RJa)),u8.push(g.so("yt-remote-connection-change",function(n){n?R7(s8(),"YouTube TV"):w8()||(R7(null,null),xJa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.$n("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.Dj(e)),SJa(e),c.start(),s8()||TJa())},VJa=function(){var a=r8().nf.$_gos();
var b=y8();b&&z8()&&(k6(a,b)||a.push(b));return JHa(a)},A8=function(){var a=WJa();
!a&&O7()&&wJa()&&(a={key:"cast-selector-receiver",name:wJa()});return a},WJa=function(){var a=VJa(),b=y8();
b||(b=w8());return g.gb(a,function(c){return b&&g6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().lg();return l6(b,a)},RJa=function(a){t8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=y8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){j7("remote",a)},r8=function(){if(!F8){var a=g.Ka("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Ka("yt.mdx.remote.currentScreenId_")},XJa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},YJa=function(){return g.Ka("yt.mdx.remote.connectData_")},v8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Ka("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||XJa("");g.Ga("yt.mdx.remote.connection_",a,void 0);q8&&(g.Db(q8,function(c){c(a)}),q8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},w8=function(){var a=g.vt();
if(!a)return null;var b=r8();if(!b)return null;b=b.lg();return l6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{XJa(a.id);var c=new h8(p8,a,x8());c.connect(b,YJa());c.subscribe("beforeDisconnect",function(d){d6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},TJa=function(){var a=w8();
a?(t8("Resume connection to: "+h6(a)),C8(a,0)):(q6(),xJa(),t8("Skipping connecting because no session screen found."))},QJa=function(){var a=x8();
if(g.Tb(a)){a=o6();var b=g.tt("yt-remote-session-name")||"",c=g.tt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Ka("yt.mdx.remote.channelParams_")||{}},SJa=function(a){a?(g.rt("yt-remote-session-app",a.app),g.rt("yt-remote-session-name",a.name)):(g.ut("yt-remote-session-app"),g.ut("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.B.call(this);
var d=this;this.B=a;this.J=b;this.ub=c;this.events=new g.bR(this);this.W=this.events.R(this.J,"onVolumeChange",function(e){ZJa(d,e)});
this.F=!1;this.suggestion=null;this.I=new g.sL(64);this.u=new g.F(this.PF,500,this);this.C=new g.F(this.QF,1E3,this);this.N=new u6(this.OQ,0,this);this.D={};this.P=new g.F(this.vG,1E3,this);this.K=new v6(this.seekTo,1E3,this);this.X=g.La;g.C(this,this.events);this.events.R(b,"onCaptionsTrackListChanged",this.BN);this.events.R(b,"captionschanged",this.MM);this.events.R(b,"captionssettingschanged",this.VF);this.events.R(b,"videoplayerreset",this.Wt);this.events.R(b,"mdxautoplaycancel",function(){d.ub.TA()});
a=this.ub;a.ma();a.subscribe("proxyStateChange",this.wE,this);a.subscribe("remotePlayerChange",this.Wp,this);a.subscribe("remoteQueueChange",this.Wt,this);a.subscribe("previousNextChange",this.tE,this);a.subscribe("nowAutoplaying",this.oE,this);a.subscribe("autoplayDismissed",this.RD,this);g.C(this,this.u);g.C(this,this.C);g.C(this,this.N);g.C(this,this.P);g.C(this,this.K);this.VF();this.Wt();this.Wp()},ZJa=function(a,b){if(J8(a)){a.ub.unsubscribe("remotePlayerChange",a.Wp,a);
var c=Math.round(b.volume),d=!!b.muted,e=a8(a.ub);if(c!==e.volume||d!==e.muted)a.ub.setVolume(c,d),a.P.start();a.ub.subscribe("remotePlayerChange",a.Wp,a)}},$Ja=function(a){a.hc(0);
a.u.stop();a.sb(new g.sL(64))},K8=function(a,b){if(J8(a)&&!a.F){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Zb(c,b));a.ub.LG(a.J.getVideoData(1).videoId,c);a.D=a8(a.ub).u}},L8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.ub.playVideo(c.videoId,b,d,e,c.playerParams,c.Kg,wHa(c));a.sb(new g.sL(1))},aKa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{XB:1});
c&&c.length?(a.J.setOption("captions","track",b),a.F=!1):(a.J.loadModule("captions"),a.F=!0)}else a.J.setOption("captions","track",{})},J8=function(a){return a8(a.ub).videoId===a.J.getVideoData(1).videoId},M8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",Z:"Connecting to your TV on web using a code will be going away soon"},{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",S:[{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Z:"Learn more"},{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],Z:"OK"}]}]}]});this.u=new g.SN(this,250);this.learnMoreButton=
this.ha("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ha("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.u);this.R(this.learnMoreButton,"click",this.B);this.R(this.okButton,"click",this.C)},N8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-popup-title",Z:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",Z:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",S:[{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-cancel"],Z:"Cancel"},{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-confirm"],
Z:"Confirm"}]}]}]});this.u=new g.SN(this,250);this.cancelButton=this.ha("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ha("ytp-mdx-privacy-popup-confirm");g.C(this,this.u);this.R(this.cancelButton,"click",this.B);this.R(this.confirmButton,"click",this.C)},O8=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",S:[{G:"div",L:"ytp-remote-display-status",S:[{G:"div",L:"ytp-remote-display-status-icon",S:[g.Zna()]},{G:"div",L:"ytp-remote-display-status-text",Z:"{{statustext}}"}]}]});this.api=a;this.u=new g.SN(this,250);g.C(this,this.u);this.R(a,"presentingplayerstatechange",this.B);bKa(this,g.AI(a))},bKa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.zJ("Error on $RECEIVER_NAME",c):b.Ib()||g.U(b,4)?g.zJ("Playing on $RECEIVER_NAME",c):g.zJ("Connected to $RECEIVER_NAME",c);a.ya("statustext",c);a.u.show()}else a.u.hide()},P8=function(a,b){g.oX.call(this,"Play on",0,a,b);
this.J=a;this.Tk={};this.R(a,"onMdxReceiversChange",this.D);this.R(a,"presentingplayerstatechange",this.D);this.D()},Q8=function(a){g.rS.call(this,a);
this.yh={key:j6(),name:"This computer"};this.Zh=null;this.subscriptions=[];this.dy=this.ub=null;this.Tk=[this.yh];this.ik=this.yh;this.Gc=new g.sL(64);this.uC=0;this.Ae=-1;this.qn=null;this.Yp=this.Ys=!1;this.lm=this.Pn=null;if(!g.VC(this.player.T())){a=this.player;var b=g.kT(a);b&&(b=b.qk())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.hP(a,b.element,4);this.Pn=new N8;g.C(this,this.Pn);g.hP(a,this.Pn.element,4);g.Q(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.Q(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.qn=new M8,g.C(this,this.qn),g.hP(a,this.qn.element,4));this.Yp=!!w8();this.Ys=!!g.tt("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.lm&&(a.player.removeEventListener("presentingplayerstatechange",a.lm),a.lm=null)},cKa=function(a,b,c){a.Gc=c;
a.player.V("presentingplayerstatechange",new g.KI(c,b))},dKa=function(a,b,c){var d=!1;
1===b?d=!a.Yp:2===b&&(d=!a.Ys);d&&g.MI(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.ik.key)if(b.key===a.yh.key)B8();
else{if(a.qn&&!a.Ys&&b!==a.yh&&"cast-selector-receiver"!==b.key&&g.eD(a.player.T()))eKa(a);else{var c;(c=!g.Q(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Yp||!a.Pn);(c?0:g.eD(a.player.T())||g.iD(a.player.T()))&&fKa(a)}a.ik=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ka(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Kg,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=wHa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Dj(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?d6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().lg(),(c=l6(c,b.key))&&C8(c,1))}},fKa=function(a){g.AI(a.player).Ib()?a.player.pauseVideo():(a.lm=function(b){dKa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.lm));
a.Pn&&a.Pn.tc();z8()||(G8=!0)},eKa=function(a){g.AI(a.player).Ib()?a.player.pauseVideo():(a.lm=function(b){dKa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.lm));
a.qn&&a.qn.tc();z8()||(G8=!0)},iIa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},K6={"'":"\\'"},gKa={},FHa={XR:"atp",U0:"ska",T_:"que",iZ:"mus",T0:"sus",BV:"dsp",n0:"seq",MY:"mic",CU:"dpa"},r6,n6="",XHa=THa("loadCastFramework")||THa("loadCastApplicationFramework"),tJa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Va(u6,g.B);g.k=u6.prototype;g.k.JI=function(a){this.D=arguments;this.u=!1;this.Xa?this.C=g.A()+this.qf:this.Xa=g.zm(this.F,this.qf)};
g.k.stop=function(){this.Xa&&(g.v.clearTimeout(this.Xa),this.Xa=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.I.apply(null,this.D)))};
g.k.ba=function(){this.stop();u6.xd.ba.call(this)};
g.k.KI=function(){this.C?(this.Xa=g.zm(this.F,this.C-g.A()),this.C=null):(this.Xa=null,this.B?this.u=!0:(this.u=!1,this.I.apply(null,this.D)))};g.u(v6,g.B);g.k=v6.prototype;g.k.KC=function(a){this.C=arguments;this.Xa||this.B?this.u=!0:w6(this)};
g.k.stop=function(){this.Xa&&(g.v.clearTimeout(this.Xa),this.Xa=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.Xa||(this.u=!1,w6(this))};
g.k.ba=function(){g.B.prototype.ba.call(this);this.stop()};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var A6=new g.Ol;g.u($Ha,g.rl);C6.prototype.u=null;C6.prototype.getOptions=function(){var a;(a=this.u)||(a={},bIa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var T8;g.Va(aIa,C6);T8=new aIa;g.k=D6.prototype;g.k.Nl=null;g.k.Ph=!1;g.k.mo=null;g.k.oz=null;g.k.Un=null;g.k.co=null;g.k.bk=null;g.k.Uk=null;g.k.mm=null;g.k.le=null;g.k.Oq=0;g.k.Uh=null;g.k.Mu=null;g.k.vk=null;g.k.lp=-1;g.k.FF=!0;g.k.vl=!1;g.k.Ew=0;g.k.iu=null;var gIa={},G6={};g.k=D6.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.RP=function(a){a=a.target;var b=this.iu;b&&3==P6(a)?b.KC():this.HG(a)};
g.k.HG=function(a){try{if(a==this.le)a:{var b=P6(this.le),c=this.le.I,d=this.le.getStatus();if(g.se&&!g.Wd(10)||g.we&&!g.Vd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pg&&!R6(this.le))break a;this.vl||4!=b||7==c||(8==c||0>=d?this.u.Gh(3):this.u.Gh(2));L6(this);var e=this.le.getStatus();this.lp=e;var f=R6(this.le);(this.Ph=200==e)?(4==b&&I6(this),this.I?(hIa(this,b,f),g.pg&&this.Ph&&3==b&&(this.D.xa(this.C,"tick",this.MP),this.C.start())):H6(this,f),this.Ph&&!this.vl&&(4==b?this.u.us(this):(this.Ph=
!1,F6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.vk=3,B6(13)):(this.vk=0,B6(14)),I6(this),J6(this))}}catch(h){this.le&&R6(this.le)}finally{}};
g.k.MP=function(){var a=P6(this.le),b=R6(this.le);this.Oq<b.length&&(L6(this),hIa(this,a,b),this.Ph&&4!=a&&F6(this))};
g.k.jP=function(a){z6((0,g.z)(this.iP,this,a),0)};
g.k.iP=function(a){this.vl||(L6(this),H6(this,a),F6(this))};
g.k.FE=function(a){z6((0,g.z)(this.hP,this,a),0)};
g.k.hP=function(a){this.vl||(I6(this),this.Ph=a,this.u.us(this),this.u.Gh(4))};
g.k.cancel=function(){this.vl=!0;I6(this)};
g.k.sP=function(){this.mo=null;var a=g.A();0<=a-this.oz?(2!=this.co&&this.u.Gh(3),I6(this),this.vk=2,B6(18),J6(this)):kIa(this,this.oz-a)};
g.k.getLastError=function(){return this.vk};g.Va(N6,g.Ol);var rIa=/^https?$/i,hKa=["POST","PUT"];g.k=N6.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.P+"; newUri="+a);b=b?b.toUpperCase():"GET";this.P=a;this.D="";this.I=0;this.va=b;this.fa=!1;this.C=!0;this.u=this.ca?cIa(this.ca):cIa(T8);this.Y=this.ca?this.ca.getOptions():T8.getOptions();this.u.onreadystatechange=(0,g.z)(this.uE,this);try{c6(Q6(this,"Opening Xhr")),this.ka=!0,this.u.open(b,String(a),!0),this.ka=!1}catch(f){c6(Q6(this,"Error opening Xhr: "+f.message));qIa(this,f);return}a=
c||"";var e=this.headers.clone();d&&BHa(d,function(f,h){e.set(h,f)});
d=g.gb(e.Ig(),oIa);c=g.v.FormData&&a instanceof g.v.FormData;!g.kb(hKa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.Ca&&(this.u.responseType=this.Ca);"withCredentials"in this.u&&this.u.withCredentials!==this.ea&&(this.u.withCredentials=this.ea);try{tIa(this),0<this.K&&(this.X=nIa(this.u),c6(Q6(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.X)),this.X?(this.u.timeout=this.K,this.u.ontimeout=(0,g.z)(this.IB,this)):this.W=g.zm(this.IB,this.K,this)),c6(Q6(this,"Sending request")),this.N=!0,this.u.send(a),this.N=!1}catch(f){c6(Q6(this,"Send error: "+f.message)),qIa(this,f)}};
g.k.IB=function(){"undefined"!=typeof g.l1&&this.u&&(this.D="Timed out after "+this.K+"ms, aborting",this.I=8,Q6(this,this.D),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.C&&(Q6(this,"Aborting"),this.C=!1,this.F=!0,this.u.abort(),this.F=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),O6(this))};
g.k.ba=function(){this.u&&(this.C&&(this.C=!1,this.F=!0,this.u.abort(),this.F=!1),O6(this,!0));N6.xd.ba.call(this)};
g.k.uE=function(){this.ma()||(this.ka||this.N||this.F?sIa(this):this.tO())};
g.k.tO=function(){sIa(this)};
g.k.isActive=function(){return!!this.u};
g.k.getStatus=function(){try{return 2<P6(this)?this.u.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.D?this.D:String(this.D)};g.k=uIa.prototype;g.k.Cw=null;g.k.Xf=null;g.k.ju=!1;g.k.HB=null;g.k.Mr=null;g.k.kx=null;g.k.Dw=null;g.k.Ia=null;g.k.qj=-1;g.k.kp=null;g.k.Eo=null;g.k.connect=function(a){this.Dw=a;a=S6(this.u,null,this.Dw);B6(3);this.HB=g.A();var b=this.u.K;null!=b?(this.kp=b[0],(this.Eo=b[1])?(this.Ia=1,vIa(this)):(this.Ia=2,U6(this))):(a6(a,"MODE","init"),this.Xf=new D6(this,void 0,void 0,void 0),this.Xf.Nl=this.Cw,E6(this.Xf,a,!1,null,!0),this.Ia=0)};
g.k.JH=function(a){if(a)this.Ia=2,U6(this);else{B6(4);var b=this.u;b.ni=b.gk.qj;a7(b,9)}a&&this.Gh(2)};
g.k.Ov=function(a){return this.u.Ov(a)};
g.k.abort=function(){this.Xf&&(this.Xf.cancel(),this.Xf=null);this.qj=-1};
g.k.GB=function(){return!1};
g.k.xE=function(a,b){this.qj=a.lp;if(0==this.Ia)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.ni=this.qj;a7(c,2);return}this.kp=c[0];this.Eo=c[1]}else c=this.u,c.ni=this.qj,a7(c,2);else if(2==this.Ia)if(this.ju)B6(7),this.kx=g.A();else if("11111"==b){if(B6(6),this.ju=!0,this.Mr=g.A(),c=this.Mr-this.HB,!g.se||g.Wd(10)||500>c)this.qj=200,this.Xf.cancel(),B6(12),T6(this.u,this,!0)}else B6(8),this.Mr=this.kx=g.A(),this.ju=!1};
g.k.us=function(){this.qj=this.Xf.lp;if(this.Xf.Ph)0==this.Ia?this.Eo?(this.Ia=1,vIa(this)):(this.Ia=2,U6(this)):2==this.Ia&&((!g.se||g.Wd(10)?!this.ju:200>this.kx-this.Mr)?(B6(11),T6(this.u,this,!1)):(B6(12),T6(this.u,this,!0)));else{0==this.Ia?B6(9):2==this.Ia&&B6(10);var a=this.u;this.Xf.getLastError();a.ni=this.qj;a7(a,2)}};
g.k.xq=function(){return this.u.xq()};
g.k.isActive=function(){return this.u.isActive()};
g.k.Gh=function(a){this.u.Gh(a)};g.k=V6.prototype;g.k.uk=null;g.k.Uo=null;g.k.Pf=null;g.k.Id=null;g.k.Bw=null;g.k.Or=null;g.k.kA=null;g.k.ts=null;g.k.Rp=0;g.k.bM=0;g.k.lf=null;g.k.kk=null;g.k.ej=null;g.k.Bl=null;g.k.gk=null;g.k.Ju=null;g.k.nn=-1;g.k.tC=-1;g.k.ni=-1;g.k.Zm=0;g.k.Lm=0;g.k.wl=8;g.Va(xIa,g.rl);g.Va(yIa,g.rl);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){B6(0);this.Bw=b;this.Uo=c||{};d&&void 0!==e&&(this.Uo.OSID=d,this.Uo.OAID=e);this.F?(z6((0,g.z)(this.CA,this,a),100),DIa(this)):this.CA(a)};
g.k.CA=function(a){this.gk=new uIa(this);this.gk.Cw=this.uk;this.gk.B=this.D;this.gk.connect(a)};
g.k.GB=function(){return 0==this.Ia};
g.k.getState=function(){return this.Ia};
g.k.EE=function(a){this.kk=null;HIa(this,a)};
g.k.DE=function(){this.ej=null;this.Id=new D6(this,this.B,"rpc",this.I);this.Id.Nl=this.uk;this.Id.Ew=0;var a=this.kA.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.B);Z5(a,"CI",this.Ju?"0":"1");Z5(a,"AID",this.nn);W6(this,a);if(!g.se||g.Wd(10))Z5(a,"TYPE","xmlhttp"),E6(this.Id,a,!0,this.ts,!1);else{Z5(a,"TYPE","html");var b=this.Id,c=!!this.ts;b.co=3;b.bk=$5(a.clone());jIa(b,c)}};
g.k.xE=function(a,b){if(0!=this.Ia&&(this.Id==a||this.Pf==a))if(this.ni=a.lp,this.Pf==a&&3==this.Ia)if(7<this.wl){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.ej){if(this.Id)if(this.Id.Un+3E3<this.Pf.Un)Y6(this),this.Id.cancel(),this.Id=null;else break a;$6(this);B6(19)}}else this.tC=c[1],0<this.tC-this.nn&&37500>c[2]&&this.Ju&&0==this.Lm&&!this.Bl&&(this.Bl=z6((0,g.z)(this.GM,this),6E3));else a7(this,11)}else b!=gKa.qU.u&&a7(this,11);else if(this.Id==
a&&Y6(this),!g.oc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.nn=e[0];e=e[1];2==this.Ia?"c"==e[0]?(this.B=e[1],this.ts=e[2],e=e[3],null!=e?this.wl=e:this.wl=6,this.Ia=3,this.lf&&this.lf.yA(),this.kA=S6(this,this.xq()?this.ts:null,this.Bw),IIa(this)):"stop"==e[0]&&a7(this,7):3==this.Ia&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.lf&&this.lf.xA(e),this.Lm=0)}}};
g.k.GM=function(){null!=this.Bl&&(this.Bl=null,this.Id.cancel(),this.Id=null,$6(this),B6(20))};
g.k.us=function(a){if(this.Id==a){Y6(this);this.Id=null;var b=2}else if(this.Pf==a)this.Pf=null,b=1;else return;this.ni=a.lp;if(0!=this.Ia)if(a.Ph)1==b?(b=A6,b.dispatchEvent(new xIa(b,a.mm?a.mm.length:0,g.A()-a.Un,this.Zm)),X6(this),this.C.length=0):IIa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ni)){if(d=1==b)this.Pf||this.kk||1==this.Ia||2<=this.Zm?d=!1:(this.kk=z6((0,g.z)(this.EE,this,a),JIa(this,this.Zm)),this.Zm++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.iI=function(a){if(!g.kb(arguments,this.Ia))throw Error("Unexpected channel state: "+this.Ia);};
g.k.BQ=function(a){a?B6(2):(B6(1),KIa(this,8))};
g.k.Ov=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new N6;a.ea=!1;return a};
g.k.isActive=function(){return!!this.lf&&this.lf.isActive(this)};
g.k.Gh=function(a){var b=A6;b.dispatchEvent(new yIa(b,a))};
g.k.xq=function(){return!(!g.se||g.Wd(10))};
g.k=LIa.prototype;g.k.yA=function(){};
g.k.xA=function(){};
g.k.wA=function(){};
g.k.Ev=function(){};
g.k.jB=function(){return{}};
g.k.isActive=function(){return!0};g.k=MIa.prototype;g.k.isEmpty=function(){return g.lb(this.u)&&g.lb(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.kb(this.u,a)||g.kb(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.PBa)(b,a);0<=c?(g.ob(b,c),b=!0):b=!1;return b||g.pb(this.B,a)};
g.k.Af=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Va(b7,g.B);g.k=b7.prototype;g.k.cP=function(){this.qf=Math.min(3E5,2*this.qf);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.qf+15E3*Math.random();this.u.Lb(a);this.B=g.A()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.qf=5E3};g.Va(c7,LIa);g.k=c7.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.Jk=function(a){return this.C.Ol(a)};
g.k.V=function(a,b){return this.C.V.apply(this.C,arguments)};
g.k.dispose=function(){this.W||(this.W=!0,g.Yf(this.C),PIa(this),g.Yf(this.B),this.B=null,this.X=function(){return""})};
g.k.ma=function(){return this.W};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.getState()){this.P="";this.B.stop();this.F=a||null;this.D=b||0;a=this.Y+"/test";b=this.Y+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ca),e=this.u;e&&(e.lf=null);d.lf=this;this.u=d;d7(this);if(this.u){d=g.L("ID_TOKEN");var f=this.u.uk||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.u.uk=f}e?(3!=e.getState()&&0==FIa(e)||e.getState(),this.u.connect(a,b,this.I,e.B,e.nn)):c?this.u.connect(a,
b,this.I,c.sessionId,c.arrayId):this.u.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Zb(c,b);this.B.isActive()||2==(this.u?this.u.getState():0)?this.K.push(c):e7(this)&&(d7(this),EIa(this.u,c))};
g.k.yA=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)EIa(this.u,a[b])}this.V("handlerOpened")};
g.k.wA=function(a){var b=2==a&&401==this.u.ni;4==a||b||this.B.start();this.V("handlerError",a)};
g.k.Ev=function(a){if(!this.B.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.jB=function(){var a={v:2};this.P&&(a.gsessionid=this.P);0!=this.D&&(a.ui=""+this.D);0!=this.N&&(a.ui=""+this.N);this.F&&g.Zb(a,this.F);return a};
g.k.xA=function(a){"S"==a[0]?this.P=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),CIa(this.u)):this.V("handlerMessage",new NIa(a[0],a[1]))};
g.k.dQ=function(){this.B.isActive();0==FIa(this.u)&&this.connect(this.F,this.D)};f7.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.F=function(a){a(Error("request timed out"))};var XIa=g.A(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Va(n7,g.O);n7.prototype.lg=function(){return this.screens};
n7.prototype.contains=function(a){return!!k6(this.screens,a)};
n7.prototype.get=function(a){return a?l6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.I,a)};g.u(o7,g.O);g.k=o7.prototype;g.k.start=function(){!this.u&&isNaN(this.Xa)&&this.MG()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.Xa)||(g.no(this.Xa),this.Xa=NaN)};
g.k.ba=function(){this.stop();g.O.prototype.ba.call(this)};
g.k.MG=function(){this.Xa=NaN;this.u=g.Vp(g7(this.I,"/pairing/get_screen"),{method:"POST",jc:{pairing_code:this.F},timeout:5E3,onSuccess:(0,g.z)(this.bR,this),onError:(0,g.z)(this.aR,this),vg:(0,g.z)(this.cR,this)})};
g.k.bR=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.C;c.name=this.D;this.V("pairingComplete",new f6(c))};
g.k.aR=function(a){this.u=null;a.status&&404==a.status?this.B>=iKa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=iKa[this.B],this.Xa=g.lo((0,g.z)(this.MG,this),a),this.B++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.cR=function(){this.u=null;this.V("pairingFailed",Error("Server not responding"))};
var iKa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Va(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.V("screenChange");!g.tt("yt-remote-lounge-token-expiration")&&aJa(this);g.no(this.u);this.u=g.lo((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);YIa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||aJa(this)};
g.k.remove=function(a,b){var c=p7(this);$Ia(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.Hu=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.ba=function(){g.no(this.u);q7.xd.ba.call(this)};
g.k.SI=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.I,"Missed "+b+" lounge tokens.")};
g.k.RI=function(a){j7(this.I,"Requesting lounge tokens failed: "+a)};g.u(t7,g.O);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.tt("yt-remote-fast-check-period")||"0",10);(this.D=g.A()-144E5<a?0:a)?v7(this):(this.D=g.A()+3E5,g.rt("yt-remote-fast-check-period",this.D),this.sy())};
g.k.isEmpty=function(){return g.Tb(this.u)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.I(),b=g.Gb(this.u,function(c,d){return c&&!!l6(a,d)},this);
u7(this,b)};
g.k.ba=function(){g.no(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.O.prototype.ba.call(this)};
g.k.sy=function(){g.no(this.C);this.C=NaN;this.B&&this.B.abort();var a=dJa(this);if(b6(a)){var b=g7(this.F,"/pairing/get_screen_availability");this.B=h7(this.F,b,{lounge_token:g.Nb(a).join(",")},(0,g.z)(this.NO,this,a),(0,g.z)(this.MO,this))}else u7(this,{}),v7(this)};
g.k.NO=function(a,b){this.B=null;var c=g.Nb(dJa(this));if(g.Bb(c,g.Nb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.od("Changing Screen set during request."),this.sy()};
g.k.MO=function(a){this.od("Screen availability failed: "+a);this.B=null;v7(this)};
g.k.od=function(a){j7("OnlineScreenService",a)};g.Va(w7,n7);g.k=w7.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.V("screenChange"),this.u.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.Hu=function(a,b,c,d){this.B.contains(a)?this.B.Hu(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.I,a),d(Error(a)))};
g.k.lg=function(a){return a?this.screens:g.rb(this.screens,g.Ge(this.C,function(b){return!this.contains(b)},this))};
g.k.NG=function(){return g.Ge(this.lg(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.OG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.Yf(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Yf(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.dR=function(a,b,c,d){g.Vp(g7(this.F,"/pairing/get_screen"),{method:"POST",jc:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new f6(f.screen||{});if(!h.name||hJa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);hJa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
vg:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ba=function(){g.Yf(this.B);g.Yf(this.u);w7.xd.ba.call(this)};
g.k.YI=function(){iJa(this);this.V("screenChange");this.u.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Va(z7,g.O);g.k=z7.prototype;g.k.getScreen=function(){return this.K};
g.k.Vt=function(a){this.K=a;this.V("sessionScreen",this.K)};
g.k.tg=function(a){this.ma()||(a&&A7(this,""+a),this.K=null,this.V("sessionScreen",null))};
g.k.info=function(a){j7(this.Y,a)};
g.k.QG=function(){return null};
g.k.Dy=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ba=function(){this.Dy("");z7.xd.ba.call(this)};g.u(B7,z7);g.k=B7.prototype;g.k.Cy=function(a){if(this.B){if(this.B==a)return;A7(this,"Overriding cast sesison with new session object");this.B.removeUpdateListener(this.F);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.B=a;this.B.addUpdateListener(this.F);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);kJa(this)};
g.k.on=function(a){this.info("launchWithParams no-op for Cast: "+g.Dj(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.z)(function(){this.tg()},this),(0,g.z)(function(){this.tg(Error("Failed to stop receiver app."))},this)):this.tg(Error("Stopping cast device witout session."))};
g.k.Dy=function(){};
g.k.ba=function(){this.info("disposeInternal");g.no(this.C);this.C=0;this.B&&(this.B.removeUpdateListener(this.F),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.B=null;z7.prototype.ba.call(this)};
g.k.zP=function(a,b){if(!this.ma())if(b){var c=x6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Dj(c));switch(d){case "mdxSessionStatus":jJa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.zB=function(a,b,c,d){gJa(this.N,this.u.label,a,this.u.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.lo((0,g.z)(this.zB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.QG=function(){return this.B};
g.k.eR=function(a){this.ma()||a||(A7(this,"Cast session died."),this.tg())};g.u(C7,z7);g.k=C7.prototype;g.k.Cy=function(a){this.C=a;this.C.addUpdateListener(this.X)};
g.k.on=function(a){this.W=a;this.F()};
g.k.stop=function(){this.B();this.B=g.La;g.no(this.D);this.C?this.C.stop((0,g.z)(this.tg,this,null),(0,g.z)(this.tg,this,"Failed to stop DIAL device.")):this.tg()};
g.k.ba=function(){this.B();this.B=g.La;g.no(this.D);this.C&&this.C.removeUpdateListener(this.X);this.C=null;z7.prototype.ba.call(this)};
g.k.hR=function(a){this.ma()||a||(A7(this,"DIAL session died."),this.B(),this.B=g.La,this.tg())};
g.k.Nw=function(a){this.P=j6();if(this.W){var b=new chrome.cast.DialLaunchResponse(!0,mJa(this));a(b);lJa(this)}else this.F=(0,g.z)(function(){g.no(this.D);this.F=g.La;this.D=NaN;var c=new chrome.cast.DialLaunchResponse(!0,mJa(this));a(c);lJa(this)},this),this.D=g.lo((0,g.z)(function(){this.F()},this),100)};
g.k.pJ=function(a,b,c){gJa(this.N,this.I.receiver.label,a,this.u.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Vt(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Nw(b,c)},this),(0,g.z)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.Nw(b,c)},this))};g.u(D7,z7);D7.prototype.stop=function(){this.tg()};
D7.prototype.Cy=function(){};
D7.prototype.on=function(){g.no(this.B);this.B=NaN;var a=l6(this.N.lg(),this.u.label);a?this.Vt(a):this.tg(Error("No such screen"))};
D7.prototype.ba=function(){g.no(this.B);this.B=NaN;z7.prototype.ba.call(this)};g.u(E7,g.O);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.N||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.xO,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.zE,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.fN,this);chrome.cast.initialize(c,(0,g.z)(function(){this.ma()||
(chrome.cast.addReceiverActionListener(this.D),UIa(),this.B.subscribe("onlineScreenChange",(0,g.z)(this.PG,this)),this.C=oJa(this),chrome.cast.setCustomReceivers(this.C,g.La,(0,g.z)(function(h){this.od("Failed to set initial custom receivers: "+g.Dj(h))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.z)(function(h){this.od("Failed to initialize API: "+g.Dj(h));
b(!1)},this))};
g.k.jQ=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.u.u.friendlyName),H7(this,null)}if(a&&b){if(!this.u){c=l6(this.B.lg(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=nJa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.La,(0,g.z)(function(e){this.od("Failed to set initial custom receivers: "+g.Dj(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.B,d),!0)}this.u.Dy(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.kQ=function(a){this.ma()?this.od("Setting connection data on disposed cast v2"):this.u?this.u.on(a):this.od("Setting connection data without a session")};
g.k.gR=function(){this.ma()?this.od("Stopping session on disposed cast v2"):this.u?(this.u.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.zE,this),(0,g.z)(this.PO,this))};
g.k.ba=function(){this.B.unsubscribe("onlineScreenChange",(0,g.z)(this.PG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=RIa,b=g.Ka("yt.mdx.remote.debug.handlers_");g.pb(b||[],a);g.Yf(this.u);g.O.prototype.ba.call(this)};
g.k.od=function(a){j7("Controller",a)};
g.k.BE=function(a,b){this.u==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.uO=function(a,b){if(!this.ma())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.V("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.B,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.B,a,this.I));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.B,a));break;default:this.od("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.od("Stopping receiver w/o session: "+a.friendlyName)}else this.od("onReceiverAction_ called without receiver.")};
g.k.fN=function(a){if(this.ma())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.od("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.od("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.od('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.B,b,this.I))}b=this.u;b.I=a;return b.I.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.pJ,b,(b.I.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Nw,b))};
g.k.zE=function(a){if(!this.ma()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.B,b),!0);else{this.od("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=l6(this.B.lg(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Yf(this.u),this.u=new B7(this.B,b),this.u.subscribe("sessionScreen",(0,g.z)(this.BE,this,this.u)),this.u.on(null));this.u.Cy(a)}}};
g.k.fR=function(){return this.u?this.u.QG():null};
g.k.PO=function(a){this.ma()||(this.od("Failed to estabilish a session: "+g.Dj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.xO=function(a){F7("Receiver availability updated: "+a);if(!this.ma()){var b=G7(this);this.F=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.k.PG=function(){this.ma()||(this.C=oJa(this),F7("Updating custom receivers: "+g.Dj(this.C)),chrome.cast.setCustomReceivers(this.C,g.La,(0,g.z)(function(){this.od("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.kQ;E7.prototype.setConnectedScreenStatus=E7.prototype.jQ;E7.prototype.stopSession=E7.prototype.gR;E7.prototype.getCastSession=E7.prototype.fR;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.ri=a.hasPrevious,this.hasNext=a.hasNext,this.N=a.playerTime,this.K=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.I=a.duration,this.P=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Ib=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.C?this.I+U7(this):this.I};
g.k.clone=function(){return new S7(Y7(this))};g.u($7,g.O);g.k=$7.prototype;g.k.getState=function(){return this.Ia};
g.k.play=function(){b8(this)?(this.u?this.u.play(null,g.La,g8(this,"play")):f8(this,"play"),e8(this,1,W7(a8(this))),this.V("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){b8(this)?(this.u?this.u.pause(null,g.La,g8(this,"pause")):f8(this,"pause"),e8(this,2,W7(a8(this))),this.V("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(b8(this)){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Ib()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.La,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.V("remotePlayerChange")}else c8(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(b8(this)){this.u?this.u.stop(null,g.La,g8(this,"stopVideo")):f8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);d8(this,a);this.V("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(b8(this)){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.z)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.od("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.z)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.od("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Sa(this.setVolume,a,b))};
g.k.LG=function(a,b){if(b8(this)){var c=a8(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Dj(b.style),g.Zb(d,c.u));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Sa(this.LG,a,b))};
g.k.setAudioTrack=function(a,b){if(b8(this)){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Dj(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.cu=function(a,b){if(b8(this)){if(a&&b){var c=a8(this);X7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Sa(this.cu,a,b))};
g.k.nextVideo=function(a,b){if(b8(this)){if(a&&b){var c=a8(this);X7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Sa(this.nextVideo,a,b))};
g.k.TA=function(){b8(this)?f8(this,"dismissAutoplay"):c8(this,this.TA)};
g.k.dispose=function(){if(3!=this.Ia){var a=this.Ia;this.Ia=3;this.V("proxyStateChange",a,this.Ia)}g.O.prototype.dispose.call(this)};
g.k.ba=function(){BJa(this);this.C=null;this.D.clear();Z7(this,null);g.O.prototype.ba.call(this)};
g.k.Gy=function(a){if((a!=this.Ia||2==a)&&3!=this.Ia&&0!=a){var b=this.Ia;this.Ia=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.lb(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.qO=function(a,b){this.V(a,b)};
g.k.QM=function(a){if(!a)this.Sp(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Sp=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),CJa(this),this.V("remotePlayerChange")};
g.k.PM=function(a){a?(CJa(this),this.V("remotePlayerChange")):this.Sp(null)};
g.k.Wy=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.XM=function(){var a=yJa();a&&Z7(this,a)};
g.k.od=function(a){j7("CP",a)};g.u(h8,g.O);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Gb.listId=c);this.Gb.videoId=d;this.Gb.index=h||0;this.Gb.state=3;V7(this.Gb,m);this.D="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Dj(l));this.u.connect({method:"setPlaylist",
params:g.Dj(l)},a,NHa())}else i8("Connecting without params"),this.u.connect({},a,NHa());EJa(this)};
g.k.dispose=function(){this.ma()||(this.V("beforeDispose"),j8(this,3));g.O.prototype.dispose.call(this)};
g.k.ba=function(){k8(this);m8(this);l8(this);g.no(this.K);this.K=NaN;g.no(this.N);this.N=NaN;this.C=null;g.Jo(this.Y);this.Y.length=0;this.u.dispose();g.O.prototype.ba.call(this);this.D=this.I=this.B=this.Gb=this.u=null};
g.k.LI=function(){this.Um(2)};
g.k.UM=function(){i8("Channel opened");this.X&&(this.X=!1,l8(this),this.W=g.lo((0,g.z)(function(){i8("Timing out waiting for a screen.");this.Um(1)},this),15E3));
RHa(OIa(this.u),this.ca)};
g.k.RM=function(){i8("Channel closed");isNaN(this.F)?q6(!0):q6();this.dispose()};
g.k.SM=function(a){q6();isNaN(this.gp())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.X=!0,i8("Channel error: "+a+" with reconnection in "+this.gp()+" ms"),j8(this,2))};
g.k.TM=function(a){a.params?i8("Received: action="+a.action+", params="+g.Dj(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.B=g.Mc(a,function(c){return new e6(c)});
a=!!g.gb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
HJa(this,a);break;case "loungeScreenDisconnected":g.qb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
HJa(this,!1);break;case "remoteConnected":var b=new e6(x6(a.params.device));g.gb(this.B,function(c){return b?c.id==b.id:!1})||xHa(this.B,b);
break;case "remoteDisconnected":b=new e6(x6(a.params.device));g.qb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":JJa(this,a);break;case "nowPlaying":LJa(this,a);break;case "onStateChange":KJa(this,a);break;case "onAdStateChange":MJa(this,a);break;case "onVolumeChanged":NJa(this,a);break;case "onSubtitlesTrackChanged":IJa(this,a);break;case "nowAutoplaying":OJa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.V("autoplayModeChange",this.D);"DISABLED"==this.D&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":PJa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.ZP=function(){if(this.C){var a=this.C;this.C=null;this.Gb.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.DI=function(){var a=3;this.ma()||(a=0,isNaN(this.gp())?e7(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.Um=function(a){i8("Disconnecting with "+a);k8(this);this.V("beforeDisconnect",a);1==a&&q6();PIa(this.u,a);this.dispose()};
g.k.BI=function(){var a=this.Gb;this.C&&(a=this.Gb.clone(),X7(a,this.C,a.index));return Y7(a)};
g.k.lQ=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.Gb.videoId&&(this.C=b.videoId,g.no(this.K),this.K=g.lo((0,g.z)(this.ZP,this),5E3));var c=[];this.Gb.listId==b.listId&&this.Gb.videoId==b.videoId&&this.Gb.index==b.index||c.push("remoteQueueChange");this.Gb.playerState==b.playerState&&this.Gb.volume==b.volume&&this.Gb.muted==b.muted&&W7(this.Gb)==W7(b)&&g.Dj(this.Gb.u)==g.Dj(b.u)||c.push("remotePlayerChange");this.Gb.reset(a);g.Db(c,function(d){this.V(d)},this)};
g.k.yB=function(){var a=this.u.I.id,b=g.gb(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.gp=function(){var a=this.u;return a.B.isActive()?a.B.B-g.A():NaN};
g.k.sI=function(){return this.D||"UNSUPPORTED"};
g.k.tI=function(){return this.I||""};
g.k.ZQ=function(){if(!isNaN(this.gp())){var a=this.u.B;g.Ym(a.u);a.start()}};
g.k.hQ=function(a,b){n8(this,a,b);GJa(this)};
g.k.KG=function(){var a=g.bq("SID","")||"",b=g.bq("SAPISID","")||"",c=g.bq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.kf(g.Re(a),2);b=g.kf(g.Re(b),2);c=g.kf(g.Re(c),2);return g.kf(g.Re(a+","+b+","+c),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Jk;h8.prototype.getProxyState=h8.prototype.DI;h8.prototype.disconnect=h8.prototype.Um;h8.prototype.getPlayerContextData=h8.prototype.BI;h8.prototype.setPlayerContextData=h8.prototype.lQ;h8.prototype.getOtherConnectedRemoteId=h8.prototype.yB;h8.prototype.getReconnectTimeout=h8.prototype.gp;h8.prototype.getAutoplayMode=h8.prototype.sI;h8.prototype.getAutoplayVideoId=h8.prototype.tI;h8.prototype.reconnect=h8.prototype.ZQ;
h8.prototype.sendMessage=h8.prototype.hQ;h8.prototype.getXsrfToken=h8.prototype.KG;g.u(o8,n7);g.k=o8.prototype;g.k.lg=function(a){return this.nf.$_gs(a)};
g.k.contains=function(a){return!!this.nf.$_c(a)};
g.k.get=function(a){return this.nf.$_g(a)};
g.k.start=function(){this.nf.$_st()};
g.k.add=function(a,b,c){this.nf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.nf.$_r(a,b,c)};
g.k.Hu=function(a,b,c,d){this.nf.$_un(a,b,c,d)};
g.k.ba=function(){for(var a=0,b=this.u.length;a<b;++a)this.nf.$_ubk(this.u[a]);this.u.length=0;this.nf=null;n7.prototype.ba.call(this)};
g.k.IJ=function(){this.V("screenChange")};
g.k.XN=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.dR;w7.prototype.$_gsppc=w7.prototype.OG;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Hu;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.lg;w7.prototype.$_gos=w7.prototype.NG;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Jk;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.u(I8,g.B);g.k=I8.prototype;g.k.ba=function(){g.B.prototype.ba.call(this);this.u.stop();this.C.stop();this.N.stop();this.X();var a=this.ub;a.unsubscribe("proxyStateChange",this.wE,this);a.unsubscribe("remotePlayerChange",this.Wp,this);a.unsubscribe("remoteQueueChange",this.Wt,this);a.unsubscribe("previousNextChange",this.tE,this);a.unsubscribe("nowAutoplaying",this.oE,this);a.unsubscribe("autoplayDismissed",this.RD,this);this.ub=this.B=null};
g.k.cD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.ub.Ia)if(J8(this)){if(!a8(this.ub).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.ub).Ib()?this.ub.pause():this.ub.play();break;case "control_play":this.ub.play();break;case "control_pause":this.ub.pause();break;case "control_seek":this.K.KC(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.MM=function(a){this.N.JI(a)};
g.k.OQ=function(a){this.cD("control_subtitles_set_track",g.Tb(a)?null:a)};
g.k.VF=function(){var a=this.J.getOption("captions","track");g.Tb(a)||K8(this,a)};
g.k.hc=function(a){this.B.hc(a,this.J.getVideoData().lengthSeconds)};
g.k.BN=function(){g.Tb(this.D)||aKa(this,this.D);this.F=!1};
g.k.wE=function(a,b){this.C.stop();2===b&&this.QF()};
g.k.Wp=function(){if(J8(this)){this.u.stop();var a=a8(this.ub);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.Ae=1;break;case 1082:case 1083:this.B.Ae=0;break;default:this.B.Ae=-1}switch(a.playerState){case 1081:case 1:this.sb(new g.sL(8));this.PF();break;case 1085:case 3:this.sb(new g.sL(9));break;case 1083:case 0:this.sb(new g.sL(2));this.K.stop();this.hc(this.J.getVideoData().lengthSeconds);break;case 1084:this.sb(new g.sL(4));break;case 2:this.sb(new g.sL(4));this.hc(W7(a));
break;case -1:this.sb(new g.sL(64));break;case -1E3:this.sb(new g.sL(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a8(this.ub).u;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,aKa(this,a));a=a8(this.ub);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.P.isActive()||this.vG()}else $Ja(this)};
g.k.tE=function(){this.J.V("mdxpreviousnextchange")};
g.k.Wt=function(){J8(this)||$Ja(this)};
g.k.oE=function(a){isNaN(a)||this.J.V("mdxnowautoplaying",a)};
g.k.RD=function(){this.J.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.ub.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.ub).playerState?L8(this,a):b&&this.ub.seekTo(a)};
g.k.vG=function(){var a=this;if(J8(this)){var b=a8(this.ub);this.events.Hb(this.W);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.W=this.events.R(this.J,"onVolumeChange",function(c){ZJa(a,c)})}};
g.k.PF=function(){this.u.stop();if(!this.ub.ma()){var a=a8(this.ub);a.Ib()&&this.sb(new g.sL(8));this.hc(W7(a));this.u.start()}};
g.k.QF=function(){this.C.stop();this.u.stop();var a=this.ub.C.getReconnectTimeout();2==this.ub.Ia&&!isNaN(a)&&this.C.start()};
g.k.sb=function(a){this.C.stop();var b=this.I;if(!g.xL(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&g.G0(this.J.app,c);this.I=a;cKa(this.B,b,a)}};g.u(M8,g.V);M8.prototype.tc=function(){this.u.show()};
M8.prototype.ib=function(){this.u.hide()};
M8.prototype.B=function(){g.JK("https://support.google.com/youtube/answer/7640706")};
M8.prototype.C=function(){d6("mdx-manual-pairing-popup-ok");this.ib()};g.u(N8,g.V);N8.prototype.tc=function(){this.u.show()};
N8.prototype.ib=function(){this.u.hide()};
N8.prototype.B=function(){d6("mdx-privacy-popup-cancel");this.ib()};
N8.prototype.C=function(){d6("mdx-privacy-popup-confirm");this.ib()};g.u(O8,g.V);O8.prototype.B=function(a){bKa(this,a.state)};g.u(P8,g.oX);P8.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Tk=g.Eb(a,this.u,this),g.pX(this,g.Mc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),this.Dc(this.u(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.u=function(a){return a.key};
P8.prototype.Ch=function(a){return"cast-selector-receiver"===a?"Cast...":this.Tk[a].name};
P8.prototype.Re=function(a){g.oX.prototype.Re.call(this,a);this.J.setOption("remote","currentReceiver",this.Tk[a]);this.Va.ib()};g.u(Q8,g.rS);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.T(),b=g.LC(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.Q(a.experiments,"mdx_load_cast_api_bootstrap_script")};UJa(b,a);this.subscriptions.push(g.so("yt-remote-before-disconnect",this.KM,this));this.subscriptions.push(g.so("yt-remote-connection-change",this.yO,this));this.subscriptions.push(g.so("yt-remote-receiver-availability-change",this.vE,this));this.subscriptions.push(g.so("yt-remote-auto-connect",this.wO,this));this.subscriptions.push(g.so("yt-remote-receiver-resumed",
this.vO,this));this.subscriptions.push(g.so("mdx-privacy-popup-confirm",this.PP,this));this.subscriptions.push(g.so("mdx-privacy-popup-cancel",this.OP,this));this.subscriptions.push(g.so("mdx-manual-pairing-popup-ok",this.CJ,this));this.vE()};
g.k.load=function(){this.player.cancelPlayback();g.rS.prototype.load.call(this);this.Zh=new I8(this,this.player,this.ub);var a=(a=YJa())?a.currentTime:0;var b=E8()?new $7(z8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.hc(a);cKa(this,this.Gc,this.Gc);g.O0(this.player.app,6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.ik=this.yh;g.Zf(this.Zh,this.ub);this.ub=this.Zh=null;g.rS.prototype.unload.call(this);g.O0(this.player.app,5);R8(this)};
g.k.ba=function(){g.to(this.subscriptions);g.rS.prototype.ba.call(this)};
g.k.Ji=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Zh.cD.apply(this.Zh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Ae};
g.k.FI=function(){return this.loaded?this.Zh.suggestion:null};
g.k.ri=function(){return this.ub?a8(this.ub).ri:!1};
g.k.hasNext=function(){return this.ub?a8(this.ub).hasNext:!1};
g.k.hc=function(a,b){this.uC=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.uC};
g.k.getProgressState=function(){var a=a8(this.ub),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ye():!a.isAdPlaying()&&this.player.ye(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+U7(a):a.D,isAtLiveHead:1>=(a.C?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.P,seekableEnd:a.C?a.B+U7(a):a.B,seekableStart:0<a.F?a.F+
U7(a):a.F}};
g.k.nextVideo=function(){this.ub&&this.ub.nextVideo()};
g.k.cu=function(){this.ub&&this.ub.cu()};
g.k.KM=function(a){1===a&&(this.dy=this.ub?a8(this.ub):null)};
g.k.yO=function(){var a=E8()?new $7(z8(),void 0):null;if(a){var b=this.ik;this.loaded&&this.unload();this.ub=a;this.dy=null;b.key!==this.yh.key&&(this.ik=b,this.load())}else g.Yf(this.ub),this.ub=null,this.loaded&&(this.unload(),(a=this.dy)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.vE=function(){var a=[this.yh],b=a.concat,c=VJa();O7()&&g.tt("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Tk=b.call(a,c);a=A8()||this.yh;S8(this,a);this.player.wa("onMdxReceiversChange")};
g.k.wO=function(){var a=A8();S8(this,a)};
g.k.vO=function(){this.ik=A8()};
g.k.PP=function(){this.Yp=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.OP=function(){this.Yp=!1;R8(this);S8(this,this.yh);this.ik=this.yh;G8=!1;H8=null;this.player.playVideo()};
g.k.CJ=function(){this.Ys=!0;R8(this);g.rt("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.qe=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Tk;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():S8(this,b)),this.loaded?this.ik:this.yh;case "quickCast":return 2===this.Tk.length&&"cast-selector-receiver"===this.Tk[1].key?(b&&Q7(),!0):!1}};
g.k.Wy=function(){this.ub.Wy()};
g.k.Oh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.dU.remote=Q8;})(_yt_player);
